"""Phase 14 — Error Analysis Framework Design.

Designs the complete post-hoc error analysis framework for PF-STGT:
regional, stress, extreme-event, temporal, graph, and root-cause studies.

Does NOT implement models, train models, or modify locked phase outputs.

Inputs (read-only):
    graphs/, targets/, architecture/, experiments/, explainability/, ablation/

Outputs:
    error_analysis/  (5 deliverables)
    results/phases/phase_14_error_analysis/  (2 reports)
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ERR_DIR = ROOT / "error_analysis"
REPORT_DIR = ROOT / "results" / "phases" / "phase_14_error_analysis"

REGIONS = [
    "Barishal",
    "Chattogram",
    "Cumilla",
    "Dhaka",
    "Khulna",
    "Mymensingh",
    "Rajshahi",
    "Rangpur",
    "Sylhet",
]

# Hybrid graph undirected degree (Phase 08 edge catalogue)
NODE_DEGREE = {
    "Dhaka": 8,
    "Cumilla": 7,
    "Mymensingh": 6,
    "Chattogram": 5,
    "Khulna": 5,
    "Rajshahi": 5,
    "Barishal": 4,
    "Rangpur": 4,
    "Sylhet": 4,
}

HIGH_CONN = [r for r, d in NODE_DEGREE.items() if d >= 6]
LOW_CONN = [r for r, d in NODE_DEGREE.items() if d <= 4]

PRIMARY_MODEL = "B07 PF-STGT (A1 seed 42)"
COMPARISON_MODELS = ["B06 T-GCN", "B04 LSTM", "B01 Linear"]
TEST_DAYS = 278
SEEDS = [42, 123, 456]


def file_md5(path: Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def error_taxonomy_rows() -> pd.DataFrame:
    rows = [
        {
            "error_id": "E1",
            "category": "overall_forecast",
            "name": "Overall Forecast Error",
            "scope": "Macro demand + national OSI on test split",
            "primary_metrics": "MAE, RMSE, MAPE, R² (Phase 10)",
            "segmentation": "None — global baseline",
            "model_scope": "All benchmarks + PF-STGT",
            "priority": "Required",
        },
        {
            "error_id": "E2",
            "category": "regional",
            "name": "Regional Error Analysis",
            "scope": "Per-node demand residuals for 9 divisions",
            "primary_metrics": "MAE, RMSE, MAPE, R² per region; Dhaka separate",
            "segmentation": "9 regions + macro aggregate",
            "model_scope": PRIMARY_MODEL,
            "priority": "Required",
        },
        {
            "error_id": "E3",
            "category": "stress",
            "name": "Operational Stress Error Analysis",
            "scope": "OSI(t+1) residuals by stress regime",
            "primary_metrics": "MAE, RMSE, R²; bias; calibration",
            "segmentation": "Low / Medium / High (train tertiles frozen)",
            "model_scope": PRIMARY_MODEL,
            "priority": "Required",
        },
        {
            "error_id": "E4",
            "category": "extreme_event",
            "name": "Extreme Event Analysis",
            "scope": "Demand spikes, supply drops, shedding periods",
            "primary_metrics": "Event recall, peak MAE, false-alarm rate",
            "segmentation": "3 event types × severity tiers",
            "model_scope": f"{PRIMARY_MODEL} + T-GCN comparison",
            "priority": "Required",
        },
        {
            "error_id": "E5",
            "category": "temporal",
            "name": "Temporal Error Analysis",
            "scope": "Weekly, seasonal, holiday error patterns",
            "primary_metrics": "MAE by DOW, month, holiday flag; seasonality ratio",
            "segmentation": "Weekday/weekend; month 1–12; holiday vs non-holiday",
            "model_scope": PRIMARY_MODEL,
            "priority": "Required",
        },
        {
            "error_id": "E6",
            "category": "graph",
            "name": "Graph Error Analysis",
            "scope": "Error vs hybrid-graph node connectivity",
            "primary_metrics": "MAE vs degree; attention–error correlation",
            "segmentation": f"High-connectivity {HIGH_CONN}; Low-connectivity {LOW_CONN}",
            "model_scope": PRIMARY_MODEL,
            "priority": "Required",
        },
    ]
    return pd.DataFrame(rows)


def write_error_taxonomy(taxonomy: pd.DataFrame) -> None:
    lines = [
        "# Error Taxonomy — Phase 14",
        "",
        f"Generated: {datetime.now(timezone.utc).date().isoformat()}",
        "Status: **FROZEN**",
        "",
        "## Objective",
        "",
        "Classify PF-STGT prediction failures into six orthogonal error categories (E1–E6)",
        "for systematic post-training analysis on the **test split only** (278 days).",
        "",
        "## Reference model and inputs",
        "",
        f"- **Primary model:** {PRIMARY_MODEL} (Phase 09/10/11)",
        "- **Residual store:** `results/error_analysis/residuals_test.parquet` (implementation phase)",
        "- **Splits:** Phase 04 chronological 70/15/15 — analysis locked to test rows",
        "- **Tasks:** Task 1 `{Region}_demand` h=1; Task 2 continuous OSI (Phase 08.5)",
        "",
        "## Error category registry",
        "",
        taxonomy[
            ["error_id", "name", "scope", "primary_metrics", "segmentation", "priority"]
        ].to_markdown(index=False),
        "",
        "---",
        "",
        "## E1 — Overall Forecast Error",
        "",
        "Baseline error profile before segmentation.",
        "",
        "```",
        "residual_demand_r(d) = D_r(d) − D̂_r(d)     ∀ r ∈ {9 regions}, d ∈ test",
        "residual_osi(d)      = OSI(d) − OSI_hat(d)",
        "```",
        "",
        "Report Phase 10 metrics + residual distribution (mean, std, skew, p95 |error|).",
        "Compare PF-STGT vs T-GCN and persistence on same test windows.",
        "",
        "---",
        "",
        "## E2 — Regional Error Analysis",
        "",
        "See `regional_error_framework.md`.",
        "",
        "Key hypothesis: Dhaka (~35.7% national share, Phase 02) drives macro error;",
        "peripheral low-degree nodes may show higher MAPE despite lower MW error.",
        "",
        "---",
        "",
        "## E3 — Operational Stress Error Analysis",
        "",
        "See `stress_error_framework.md`.",
        "",
        "Stratify by **train-frozen OSI tertiles** (Low/Medium/High) applied to test labels.",
        "Test split stress shift: ~16% Low / 24% Medium / 60% High (Phase 08.5 distribution).",
        "",
        "---",
        "",
        "## E4 — Extreme Event Analysis",
        "",
        "See `extreme_event_framework.md`.",
        "",
        "Three event classes aligned with Bangladesh grid operations:",
        "",
        "1. **Demand spikes** — national or regional demand > train μ + 2σ",
        "2. **Supply drops** — `generation_reserve` or `Highest Generation` drop > train p10",
        "3. **Load shedding** — `any_regional_shedding=1` or regional `_load > 0`",
        "",
        "---",
        "",
        "## E5 — Temporal Error Analysis",
        "",
        "### Segmentation axes",
        "",
        "| Axis | Field | Bins | Rationale |",
        "| --- | --- | --- | --- |",
        "| Weekly | `Day of the week` / Date | Mon–Sun | Phase 02 weekday load shape |",
        "| Seasonal | `Month` / Date | 1–12 | Month-9 summer peak (Phase 02) |",
        "| Holiday | `Holiday_cat` / `Holiday name` | holiday vs non-holiday | Calendar exogenous (Phase 01) |",
        "",
        "### Metrics per bin",
        "",
        "```",
        "MAE_bin   = mean(|residual|) over days in bin",
        "n_bin     = sample count (flag bins with n < 15 as low-confidence)",
        "seasonality_ratio = MAE_month9 / MAE_month_overall",
        "```",
        "",
        "### Expected failure modes",
        "",
        "- **Month 9 (Apr–Oct peak):** cooling-driven demand; temperature_anomaly_month sensitivity",
        "- **Fridays / pre-holiday:** calendar shift not fully captured by T=7 window",
        "- **Post-2023 test period:** upward demand trend extrapolation error",
        "",
        "### Outputs",
        "",
        "```",
        "results/error_analysis/temporal/mae_by_dow.csv",
        "results/error_analysis/temporal/mae_by_month.csv",
        "results/error_analysis/temporal/mae_holiday_vs_nonholiday.csv",
        "results/error_analysis/temporal/temporal_error_heatmap.png",
        "```",
        "",
        "---",
        "",
        "## E6 — Graph Error Analysis",
        "",
        "### Connectivity groups (Phase 08 hybrid graph)",
        "",
        "| Group | Regions | Mean degree |",
        "| --- | --- | --- |",
        f"| High-connectivity | {', '.join(HIGH_CONN)} | ≥ 6 |",
        f"| Mid-connectivity | Chattogram, Khulna, Rajshahi | 5 |",
        f"| Low-connectivity | {', '.join(LOW_CONN)} | ≤ 4 |",
        "",
        "### Analysis protocol",
        "",
        "1. Compute per-region test MAE; correlate with node degree (Spearman ρ).",
        "2. Compare macro MAE on high- vs low-connectivity subsets.",
        "3. Overlay spatial attention mass on hybrid edges for high-error days.",
        "4. Cross-reference Phase 13 A2 (−Graph) degradation by connectivity group.",
        "",
        "### Hypotheses",
        "",
        "- Hub node **Dhaka** (degree 8): lower MAPE via rich neighbor signal; errors from national trend.",
        "- **Low-connectivity** nodes (Barishal, Rangpur, Sylhet): higher MAPE; graph ablation hurts more.",
        "- Non-geographic hybrid edges (Cumilla–Khulna, Cumilla–Sylhet): attention should activate on coupled errors.",
        "",
        "### Outputs",
        "",
        "```",
        "results/error_analysis/graph/mae_vs_degree.csv",
        "results/error_analysis/graph/high_vs_low_connectivity_summary.csv",
        "results/error_analysis/graph/attention_error_cases.csv",
        "```",
        "",
        "## Cross-category interaction matrix",
        "",
        "| Interaction | Analysis |",
        "| --- | --- |",
        "| E2 × E5 | Regional MAE heatmap by month |",
        "| E3 × E4 | OSI error on shedding days |",
        "| E4 × E5 | Extreme demand spikes by season |",
        "| E6 × E2 | Degree vs regional MAPE |",
        "| E3 × E6 | Stress error on high- vs low-connectivity aggregate load |",
        "",
        "## Implementation artefact index",
        "",
        "```",
        "results/error_analysis/error_taxonomy_index.csv",
        "results/error_analysis/residuals_test.parquet",
        "results/error_analysis/error_segment_summary.csv",
        "```",
        "",
    ]
    (ERR_DIR / "error_taxonomy.md").write_text("\n".join(lines))
    taxonomy.to_csv(ERR_DIR / "error_taxonomy_index.csv", index=False)


def write_regional_error_framework() -> None:
    degree_table = pd.DataFrame(
        [{"region": r, "graph_degree": NODE_DEGREE[r], "connectivity_tier": (
            "High" if r in HIGH_CONN else ("Low" if r in LOW_CONN else "Mid")
        )} for r in REGIONS]
    )
    lines = [
        "# Regional Error Framework — Phase 14",
        "",
        f"Generated: {datetime.now(timezone.utc).date().isoformat()}",
        "Status: **FROZEN**",
        "",
        "## Scope (E2)",
        "",
        "Per-region demand forecast error analysis for all 9 division nodes on the test split.",
        "",
        "## Regions under study",
        "",
        ", ".join(REGIONS) + ".",
        "",
        "**Dhaka** reported separately (Phase 10 rule): ~35.65% mean national demand share (Phase 02).",
        "",
        "## Graph connectivity context (Phase 08)",
        "",
        degree_table.to_markdown(index=False),
        "",
        "## Residual definitions",
        "",
        "```",
        "e_r(d) = D_r(d) − D̂_r(d)          signed residual (MW)",
        "|e_r(d)|                         absolute error",
        "APE_r(d) = |e_r(d)| / |D_r(d)| × 100%   (exclude D_r=0)",
        "```",
        "",
        "## Primary metrics (per region, test split)",
        "",
        "| Metric | Formula | Report |",
        "| --- | --- | --- |",
        "| MAE_r | mean(|e_r|) | MW + rank |",
        "| RMSE_r | sqrt(mean(e_r²)) | MW |",
        "| MAPE_r | mean(APE_r) | % |",
        "| R²_r | 1 − SS_res/SS_tot | unitless |",
        "| Bias_r | mean(e_r) | MW (systematic over/under) |",
        "| p95_|e|_r | 95th percentile | MW tail risk |",
        "",
        "## Segmentation dimensions",
        "",
        "| Dimension | Purpose |",
        "| --- | --- |",
        "| All test days | Baseline regional leaderboard |",
        "| High-error days | Top 10% macro MAE days — which regions drive spike? |",
        "| Connectivity tier | High vs mid vs low graph degree |",
        "| Demand share quartile | Large vs small regions (regional_demand_share) |",
        "",
        "## Regional failure hypotheses",
        "",
        "| Region | Expected failure mode | Evidence |",
        "| --- | --- | --- |",
        "| Dhaka | Trend extrapolation; national peak driver | Phase 02 dominance |",
        "| Chattogram | Port/industrial volatility | High demand variance |",
        "| Mymensingh | Sparse shedding in OSI c1 (Phase 12) | Stress attribution design |",
        "| Barishal / Rangpur / Sylhet | Higher MAPE (low degree, smaller MW) | Graph E6 |",
        "| Cumilla | Benefit from hybrid non-geo edges | ρ≈0.93 Barishal–Cumilla |",
        "",
        "## Comparison protocol",
        "",
        "1. PF-STGT vs **T-GCN** per-region ΔMAE (graph baseline).",
        "2. PF-STGT vs **LSTM** — quantify graph gain on low-connectivity subset.",
        "3. Phase 13 **A2 (−Graph)** regional ΔMAE — confirm spatial module helps periphery most.",
        "",
        "## Visualisation spec",
        "",
        "| Figure | Content |",
        "| --- | --- |",
        "| `regional_mae_bar.png` | 9-region MAE ranked |",
        "| `regional_error_boxplot.png` | Residual distribution per region |",
        "| `dhaka_vs_macro.png` | Dhaka MAE vs macro MAE time series |",
        "| `regional_mae_by_month_heatmap.png` | E2 × E5 interaction |",
        "",
        "## Output artefacts",
        "",
        "```",
        "results/error_analysis/regional/per_region_metrics_test.csv",
        "results/error_analysis/regional/regional_error_ranking.csv",
        "results/error_analysis/regional/regional_bias_report.csv",
        "results/error_analysis/regional/connectivity_tier_mae.csv",
        "```",
        "",
        "## Acceptance criteria",
        "",
        "- All 9 regions reported with n=278 test days each.",
        "- Dhaka MAE and macro MAE both reported in summary table.",
        "- At least one region where PF-STGT beats T-GCN on MAE (validates graph value).",
        "",
    ]
    (ERR_DIR / "regional_error_framework.md").write_text("\n".join(lines))


def write_stress_error_framework() -> None:
    lines = [
        "# Stress Error Framework — Phase 14",
        "",
        f"Generated: {datetime.now(timezone.utc).date().isoformat()}",
        "Status: **FROZEN**",
        "",
        "## Scope (E3)",
        "",
        "Operational Stress Index (OSI) forecast error analysis for Task 2 (Phase 08.5 SF-04).",
        "",
        "## Target definition (frozen)",
        "",
        "```",
        "c1 = L_total / D_total              shedding intensity",
        "c2 = 1 − GR / Highest_Gen           reserve margin",
        "c3 = TOL / Highest_Gen              limitation stack",
        "OSI = mean(minmax_train(c1), minmax_train(c2), minmax_train(c3))  ∈ [0, 1]",
        "```",
        "",
        "**Leakage rule:** same-day OSI never an input when predicting OSI(t+1) (Phase 08.5/12).",
        "",
        "## Stress regime segmentation",
        "",
        "Use **train-frozen tertile boundaries** on OSI (Phase 08.5 `stress_3class`):",
        "",
        "| Regime | Definition | Train % | Test % (approx) |",
        "| --- | --- | --- | --- |",
        "| **Low Stress** | OSI ≤ train tertile Q1 | 33.4% | 16.2% |",
        "| **Medium Stress** | Q1 < OSI ≤ Q2 | 33.3% | 24.1% |",
        "| **High Stress** | OSI > Q2 | 33.4% | 59.7% |",
        "",
        "Test-period shift toward high stress (63% any shedding days) — report regime sample counts.",
        "",
        "## Primary metrics by regime",
        "",
        "| Metric | Formula | Interpretation |",
        "| --- | --- | --- |",
        "| MAE_regime | mean(|OSI − OSI_hat|) | Overall stress accuracy |",
        "| RMSE_regime | sqrt(mean((OSI − OSI_hat)²)) | Penalises large misses |",
        "| R²_regime | 1 − SS_res/SS_tot | Explained variance |",
        "| Bias_regime | mean(OSI_hat − OSI) | Over/under-prediction of stress |",
        "| Calibration slope | linreg(OSI, OSI_hat) slope | 1.0 = well calibrated |",
        "",
        "## Secondary diagnostics",
        "",
        "| Diagnostic | Method |",
        "| --- | --- |",
        "| Component attribution error | Compare argmax(c1,c2,c3) to SHAP driver (Phase 12) |",
        "| Shedding alignment | OSI error when `any_regional_shedding=1` vs 0 |",
        "| Persistence gap | MAE vs OSI(t) persistence baseline (Phase 10) |",
        "| High-stress recall | Fraction of High regime with OSI_hat > train Q2 |",
        "",
        "## Expected failure modes",
        "",
        "| Regime | Expected error pattern | Root-cause link |",
        "| --- | --- | --- |",
        "| Low | Over-prediction (bias > 0) | Model trained on fewer low-stress test days |",
        "| Medium | Highest calibration uncertainty | Boundary instability (Phase 08.5 limitation) |",
        "| High | Under-prediction of peak OSI | Sparse extreme c1/c3 combinations |",
        "",
        "## Multi-task cross-check (Phase 13 A4)",
        "",
        "Compare stress metrics on A1 vs demand-only A4 (stress head absent on A4).",
        "Demand error on high-stress days: does multi-task A1 reduce |e_r| when OSI is High?",
        "",
        "## Visualisation spec",
        "",
        "| Figure | Content |",
        "| --- | --- |",
        "| `osi_scatter_by_regime.png` | OSI vs OSI_hat coloured by regime |",
        "| `osi_error_violin.png` | |OSI − OSI_hat| by Low/Med/High |",
        "| `osi_component_error_bars.png` | MAE on days dominated by c1 vs c2 vs c3 |",
        "",
        "## Output artefacts",
        "",
        "```",
        "results/error_analysis/stress/stress_metrics_by_regime.csv",
        "results/error_analysis/stress/stress_calibration_report.csv",
        "results/error_analysis/stress/stress_error_on_shedding_days.csv",
        "results/error_analysis/stress/stress_component_driver_errors.csv",
        "```",
        "",
        "## Acceptance criteria",
        "",
        "- All three regimes reported with sample counts.",
        "- PF-STGT stress MAE < persistence baseline on test (Phase 10 gate).",
        "- High-stress regime analysed separately (majority of test days).",
        "",
    ]
    (ERR_DIR / "stress_error_framework.md").write_text("\n".join(lines))


def write_extreme_event_framework() -> None:
    lines = [
        "# Extreme Event Framework — Phase 14",
        "",
        f"Generated: {datetime.now(timezone.utc).date().isoformat()}",
        "Status: **FROZEN**",
        "",
        "## Scope (E4)",
        "",
        "Evaluate PF-STGT under operational extremes: demand spikes, supply drops, and load shedding.",
        "Aligned with Phase 07B resilience literature and Phase 02 sparse `_load` signal.",
        "",
        "## Event taxonomy",
        "",
        "### Event Type 1 — Demand spikes",
        "",
        "| Tier | Rule (train-fitted thresholds) |",
        "| --- | --- |",
        "| Regional spike | `{Region}_demand(t+1) > μ_r,train + 2σ_r,train` |",
        "| National spike | `total_regional_demand(t+1) > μ_nat,train + 2σ_nat,train` |",
        "| Severe | > μ + 3σ or top 5% of train demand |",
        "",
        "### Event Type 2 — Supply drops",
        "",
        "| Tier | Rule |",
        "| --- | --- |",
        "| Reserve stress | `generation_reserve(t+1) < Q10_train` |",
        "| Generation drop | `Highest Generation(t+1) < Q10_train` |",
        "| Compound | reserve stress AND demand spike |",
        "",
        "### Event Type 3 — Load shedding periods",
        "",
        "| Tier | Rule |",
        "| --- | --- |",
        "| Any shedding | `any_regional_shedding(t+1) = 1` (test: ~63% days) |",
        "| Regional shed | `{Region}_load(t+1) > 0` |",
        "| Multi-region | `shedding_region_count(t+1) ≥ 2` |",
        "",
        "All thresholds computed on **train split only**; applied to test labels at t+1.",
        "",
        "## Evaluation metrics per event type",
        "",
        "### Demand task",
        "",
        "| Metric | Definition |",
        "| --- | --- |",
        "| Event MAE | mean(|e_r|) on event days only |",
        "| Event MAPE | mean(APE_r) on event days |",
        "| Spike recall | fraction of spike days with |e_r| < 1.5 × median |e| |",
        "| Peak under-prediction rate | P(D̂ < D | spike day) |",
        "",
        "### Stress task",
        "",
        "| Metric | Definition |",
        "| --- | --- |",
        "| High-OSI event MAE | MAE on OSI > train Q90 |",
        "| Shedding-day OSI MAE | MAE when any_regional_shedding=1 |",
        "| Missed stress alert | OSI > Q2 but OSI_hat < Q2 |",
        "",
        "## Severity stratification",
        "",
        "```",
        "severity_score = rank(normalize(|Δdemand|) + normalize(OSI) + shedding_flag)",
        "Report metrics for severity terciles: Mild / Moderate / Severe",
        "```",
        "",
        "## Benchmark comparison",
        "",
        "| Comparison | Purpose |",
        "| --- | --- |",
        "| PF-STGT vs T-GCN | Graph model on shedding days |",
        "| PF-STGT vs LSTM | Temporal-only on demand spikes |",
        "| PF-STGT vs persistence | Stress on high-OSI events |",
        "",
        "## Case study protocol (top-K events)",
        "",
        "Select **K=10** worst macro-error days on test; for each document:",
        "",
        "1. Event type(s) triggered",
        "2. Per-region error contribution",
        "3. OSI residual",
        "4. Phase 12 XAI summary (SHAP + attention)",
        "5. Root-cause label (see `root_cause_analysis_protocol.md`)",
        "",
        "## Visualisation spec",
        "",
        "| Figure | Content |",
        "| --- | --- |",
        "| `extreme_event_mae_comparison.png` | MAE: normal vs event days |",
        "| `demand_spike_scatter.png` | Actual vs predicted on spike days |",
        "| `shedding_timeline.png` | Shedding flag vs |OSI − OSI_hat| |",
        "",
        "## Output artefacts",
        "",
        "```",
        "results/error_analysis/extreme/event_definitions.csv",
        "results/error_analysis/extreme/event_metrics_by_type.csv",
        "results/error_analysis/extreme/top10_worst_days.csv",
        "results/error_analysis/extreme/extreme_event_case_studies.md",
        "```",
        "",
        "## Acceptance criteria",
        "",
        "- All three event types evaluated with train-frozen thresholds.",
        "- Shedding-period analysis mandatory (operational relevance for Bangladesh grid).",
        "- Top-10 worst-day case studies linked to root-cause protocol.",
        "",
    ]
    (ERR_DIR / "extreme_event_framework.md").write_text("\n".join(lines))


def write_root_cause_analysis_protocol() -> None:
    lines = [
        "# Root Cause Analysis Protocol — Phase 14",
        "",
        f"Generated: {datetime.now(timezone.utc).date().isoformat()}",
        "Status: **FROZEN**",
        "",
        "## Objective",
        "",
        "Systematically explain **why** PF-STGT errors occur by triangulating:",
        "",
        "1. Feature attribution review (Phase 12 L1 SHAP + Permutation)",
        "2. Attention review (Phase 12 L3–L4 graph/temporal attention)",
        "3. Stress attribution review (Phase 12 L5 OSI component decomposition)",
        "",
        "## Trigger conditions",
        "",
        "Run root-cause analysis when ANY hold:",
        "",
        "| Trigger | Threshold |",
        "| --- | --- |",
        "| High macro error | Daily macro MAE > test p90 |",
        "| Regional outlier | |e_r| > 2 × MAE_r for any region |",
        "| Stress miss | |OSI − OSI_hat| > 0.15 on High-stress day |",
        "| Extreme event | Day flagged in E4 taxonomy |",
        "| Ablation surprise | A2/A3 regional error pattern contradicts hypothesis |",
        "",
        "## Three-pathway methodology",
        "",
        "### Pathway 1 — Feature attribution review",
        "",
        "**Tools:** GradientSHAP grouped coalitions + Permutation importance (Phase 12).",
        "",
        "**Procedure:**",
        "",
        "1. For flagged day d, compute SHAP for demand head (9 outputs) and stress head.",
        "2. Rank feature groups G1–G11 (Phase 05A batches).",
        "3. Compare top-3 SHAP groups to Permutation top-3 on validation (consistency check).",
        "4. Label root cause if top group maps to known driver:",
        "",
        "| SHAP group | Root-cause label |",
        "| --- | --- |",
        "| G1–G2 (lags, rolling) | Temporal memory failure |",
        "| G3–G4 (regional load/intensity) | Shedding / local demand miss |",
        "| G5–G6 (calendar, season) | Seasonal/holiday miss |",
        "| G7–G8 (grid national) | Supply/reserve miss |",
        "| G9–G11 (weather, limitations) | Exogenous shock miss |",
        "",
        "**Output:** `feature_attribution_review_{date}.csv`",
        "",
        "### Pathway 2 — Attention review",
        "",
        "**Tools:** Graph Transformer spatial attention + Temporal Encoder attention (Phase 09/12).",
        "",
        "**Procedure:**",
        "",
        "1. Export α_ij (spatial) and α_t (temporal) for day d.",
        "2. Compare spatial attention to hybrid adjacency — identify unexpected high-weight edges.",
        "3. Check if error region r receives insufficient attention from neighbors.",
        "4. Compute **attention deficit score**:",
        "",
        "```",
        "ADS_r = MAE_r / (Σ_j α_rj + ε)     high ADS → error despite low attention to r",
        "```",
        "",
        "5. Cross-check Phase 13 A2: if −Graph ablation error correlates with ADS, graph module failure confirmed.",
        "",
        "**Output:** `attention_review_{date}.csv`, `spatial_attention_overlay.png`",
        "",
        "### Pathway 3 — Stress attribution review",
        "",
        "**Tools:** SHAP on stress head + ground-truth c1,c2,c3 decomposition (Phase 12 L5).",
        "",
        "**Procedure:**",
        "",
        "1. For high |OSI − OSI_hat| days, compute SHAP on OSI_hat.",
        "2. Decompose actual OSI at t+1 into c1 (shedding), c2 (reserve), c3 (limitations).",
        "3. Assign driver: `driver = argmax(minmax(c1), minmax(c2), minmax(c3))`.",
        "4. Compare driver to top SHAP group — build confusion matrix:",
        "",
        "```",
        "results/explainability/stress/stress_driver_confusion.csv  (Phase 12)",
        "→ extended in Phase 14 with error-conditioned rows only",
        "```",
        "",
        "5. If demand error and stress error co-occur, label **compound operational failure**.",
        "",
        "**Output:** `stress_attribution_review_{date}.csv`",
        "",
        "## Root-cause label taxonomy",
        "",
        "| Label ID | Name | Criteria |",
        "| --- | --- | --- |",
        "| RC-T1 | Temporal miss | Top SHAP G1–G2; low α on recent lags |",
        "| RC-S1 | Spatial/graph miss | High ADS; A2 ablation worse on region |",
        "| RC-C1 | Calendar/season miss | Holiday or month-9; G5–G6 dominant |",
        "| RC-G1 | Supply/reserve miss | c2 dominant; G7–G8 SHAP |",
        "| RC-L1 | Shedding miss | c1 dominant; shedding day; G3/G11 |",
        "| RC-X1 | Exogenous shock | Limitation/temperature spike; G9–G11 |",
        "| RC-M1 | Multi-task interference | Demand ok, stress bad (or vice versa) on same day |",
        "| RC-U1 | Uncertain | No pathway agreement (< 2/3 concur) |",
        "",
        "## Triangulation decision rule",
        "",
        "Assign final root cause when **≥ 2 of 3 pathways agree** on the same label family:",
        "",
        "```",
        "families: {Temporal}, {Spatial}, {Calendar}, {Supply}, {Shedding}, {Exogenous}",
        "```",
        "",
        "If only 1 pathway fires → label **RC-U1 Uncertain** and flag for manual review.",
        "",
        "## Integration with ablation (Phase 13)",
        "",
        "| Ablation | Root-cause use |",
        "| --- | --- |",
        "| A2 (−Graph) | Validate RC-S1 labels — graph removal should worsen same regions |",
        "| A3 (−Transformer) | Validate RC-T1 — temporal removal worsens same days |",
        "| A4 (demand-only) | Validate RC-M1 — stress errors without stress head |",
        "| A5-GEO | Validate hybrid-edge RC-S1 cases (Cumilla–Khulna etc.) |",
        "",
        "## Workflow summary",
        "",
        "```",
        "1. Compute residuals (test) → flag triggers",
        "2. For each flagged day:",
        "     a. Feature attribution review  (Pathway 1)",
        "     b. Attention review            (Pathway 2)",
        "     c. Stress attribution review   (Pathway 3)",
        "3. Triangulate → assign RC label",
        "4. Aggregate RC labels → error taxonomy heatmap",
        "5. Feed findings back to paper Discussion + operator brief",
        "```",
        "",
        "## Output artefacts",
        "",
        "```",
        "results/error_analysis/root_cause/rc_label_registry.csv",
        "results/error_analysis/root_cause/flagged_days.csv",
        "results/error_analysis/root_cause/rc_triangulation_log.csv",
        "results/error_analysis/root_cause/rc_summary_by_category.csv",
        "results/error_analysis/root_cause/root_cause_case_studies.md",
        "```",
        "",
        "## Acceptance criteria",
        "",
        "- All three pathways documented and executable post-training.",
        "- Triangulation rule frozen (≥2/3 agreement).",
        "- RC labels mapped to E1–E6 error categories for cross-tabulation.",
        "",
    ]
    (ERR_DIR / "root_cause_analysis_protocol.md").write_text("\n".join(lines))


def write_temporal_section_note() -> None:
    """Temporal analysis is defined in error_taxonomy E5; no separate deliverable required."""
    pass


def write_summary(taxonomy: pd.DataFrame, locked_md5: dict[str, str]) -> None:
    lines = [
        "# Phase 14 — Error Analysis Framework Summary",
        "",
        f"- Completion date: {datetime.now(timezone.utc).date().isoformat()}",
        f"- Primary model: **{PRIMARY_MODEL}**",
        f"- Error categories: **{len(taxonomy)}** (E1–E6)",
        f"- Test analysis window: **{TEST_DAYS} days** (no analysis executed in this phase)",
        "",
        "## Framework components",
        "",
        "| Component | Category | Deliverable |",
        "| --- | --- | --- |",
        "| Overall error | E1 | error_taxonomy.md |",
        "| Regional error | E2 | regional_error_framework.md |",
        "| Stress error | E3 | stress_error_framework.md |",
        "| Extreme events | E4 | extreme_event_framework.md |",
        "| Temporal error | E5 | error_taxonomy.md (§E5) |",
        "| Graph error | E6 | error_taxonomy.md (§E6) + regional framework |",
        "| Root-cause analysis | RC | root_cause_analysis_protocol.md |",
        "",
        "## Root-cause pathways (Phase 12 integration)",
        "",
        "1. **Feature attribution** — SHAP + Permutation (L1)",
        "2. **Attention review** — spatial + temporal (L3–L4)",
        "3. **Stress attribution** — OSI component decomposition (L5)",
        "",
        "Triangulation: ≥2/3 pathway agreement → assign RC label.",
        "",
        "## Deliverables",
        "",
        "### error_analysis/",
        "- error_taxonomy.md",
        "- error_taxonomy_index.csv",
        "- regional_error_framework.md",
        "- stress_error_framework.md",
        "- extreme_event_framework.md",
        "- root_cause_analysis_protocol.md",
        "",
        "### results/phases/phase_14_error_analysis/",
        "- error_analysis_summary.md",
        "- error_analysis_decision_report.md",
        "",
        "## Scope compliance",
        "",
        "- Error analysis framework design only.",
        "- **No model implementation or training.**",
        "- **No experimental results or residual files generated.**",
        "- Locked phase outputs not modified.",
        "",
        "## Locked input integrity",
        "",
    ]
    for path, md5 in locked_md5.items():
        lines.append(f"- `{path}` MD5: `{md5}`")
    lines += [
        "",
        "## Status",
        "",
        "Ready for post-training error analysis execution (after model training phase).",
        "",
    ]
    (REPORT_DIR / "error_analysis_summary.md").write_text("\n".join(lines))


def write_decision_report(taxonomy: pd.DataFrame) -> None:
    lines = [
        "# Error Analysis Decision Report — Phase 14",
        "",
        f"Generated: {datetime.now(timezone.utc).date().isoformat()}",
        "",
        "## Design rationale",
        "",
        "### Why six error categories?",
        "",
        "PF-STGT is a multi-task spatio-temporal graph model (Phase 09). Failures can arise",
        "in spatial coupling (E2/E6), temporal seasonality (E5), stress regime (E3), or operational",
        "extremes (E4). E1 provides the global baseline; root-cause triangulation explains *why*.",
        "",
        "### Regional analysis (E2)",
        "",
        "Phase 10 mandates Dhaka separate reporting. Phase 08 hybrid graph gives heterogeneous",
        f"node degrees (Dhaka=8, periphery=4). Regional framework links to E6 connectivity tiers.",
        "",
        "### Stress analysis (E3)",
        "",
        "Continuous OSI (Phase 08.5) with train-frozen tertiles avoids validation leakage.",
        "Test-period shift to 60% High stress requires regime-stratified metrics, not pooled MAE alone.",
        "",
        "### Extreme events (E4)",
        "",
        "Phase 02: shedding sparse in train (~18%) but dense in test (~63%). Extreme-event",
        "framework uses train-fitted thresholds applied to t+1 labels — critical for operator relevance.",
        "",
        "### Temporal analysis (E5)",
        "",
        "Phase 02 identified month-9 peak and multi-year trend. Weekly/holiday bins use Phase 01",
        "calendar fields. Low-confidence flag for bins with n<15.",
        "",
        "### Root-cause analysis",
        "",
        "Phase 12 hybrid XAI stack is post-hoc by design. Phase 14 consumes SHAP, attention,",
        "and stress decomposition outputs — no new XAI methods introduced.",
        "Triangulation prevents over-interpreting any single attribution method (Jain & Wallace 2019).",
        "",
        "## Category registry",
        "",
        taxonomy[["error_id", "category", "name", "priority"]].to_markdown(index=False),
        "",
        "## Graph connectivity groups (E6)",
        "",
        f"- **High:** {', '.join(HIGH_CONN)} (degree ≥ 6)",
        f"- **Low:** {', '.join(LOW_CONN)} (degree ≤ 4)",
        "",
        "## Expected findings (hypotheses — to validate post-training)",
        "",
        "| Category | Hypothesis |",
        "| --- | --- |",
        "| E2 | Dhaka largest MW error; periphery highest MAPE |",
        "| E3 | Largest OSI error in High-stress regime |",
        "| E4 | Shedding-day demand MAE > non-shedding |",
        "| E5 | Month-9 MAE > annual mean |",
        "| E6 | Low-connectivity regions benefit most from graph module |",
        "| RC | RC-L1 and RC-G1 dominate on test (shedding + reserve stress) |",
        "",
        "## Dependencies",
        "",
        "| Prerequisite phase | Required artefact |",
        "| --- | --- |",
        "| Phase 10 | Trained PF-STGT + test predictions |",
        "| Phase 12 | SHAP/attention export pipeline |",
        "| Phase 13 | A2/A3 ablation predictions for RC-S1/RC-T1 validation |",
        "",
    ]
    (REPORT_DIR / "error_analysis_decision_report.md").write_text("\n".join(lines))


def main() -> None:
    ERR_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    locked_paths = {
        "data/features/train_features.parquet": ROOT / "data" / "features" / "train_features.parquet",
        "data/interim/bangladesh_smartgrid_clean.parquet": ROOT / "data" / "interim" / "bangladesh_smartgrid_clean.parquet",
        "graphs/adjacency_matrix.csv": ROOT / "graphs" / "adjacency_matrix.csv",
        "explainability/xai_strategy.md": ROOT / "explainability" / "xai_strategy.md",
        "ablation/ablation_plan.md": ROOT / "ablation" / "ablation_plan.md",
    }
    locked_md5 = {k: file_md5(v) for k, v in locked_paths.items() if v.exists()}

    taxonomy = error_taxonomy_rows()
    write_error_taxonomy(taxonomy)
    write_regional_error_framework()
    write_stress_error_framework()
    write_extreme_event_framework()
    write_root_cause_analysis_protocol()
    write_summary(taxonomy, locked_md5)
    write_decision_report(taxonomy)

    print("Phase 14 error analysis framework design complete.")
    print(f"Error categories: {len(taxonomy)} (E1–E6)")
    print(f"Reports -> {ERR_DIR.relative_to(ROOT)} , {REPORT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
